paths = {...
     pwd,...
     'export_fig',...
     'Behavior', ...
     'Background', ...
     'Gui', ...
     'ImageAlignment', ...
     'MindControlAccessUtils', ...
     'MiscTools', ...
     'MiscTools/cm_and_cb_utilities', ...
     'MiscTools/demon_registration_version_8f', ...
     'MiscTools/demon_registration_version_8f/functions', ...
     'MiscTools/demon_registration_version_8f/functions_affine', ...
     'MiscTools/demon_registration_version_8f/functions_nonrigid', ...
     'MiscTools/demon_registration_version_8f/images', ...
     'MiscTools/demon_registration_version_8f/literature', ...
     'MiscTools/demon_registration_version_8f_bad', ...
     'MiscTools/demon_registration_version_8f_bad/functions', ...
     'MiscTools/demon_registration_version_8f_bad/functions_affine', ...
     'MiscTools/demon_registration_version_8f_bad/functions_nonrigid', ...
     'MiscTools/flann', ...
     'MiscTools/nonrigid_version23', ...
     'MiscTools/nonrigid_version23/functions', ...
     'MiscTools/nonrigid_version23/functions_affine', ...
     'MiscTools/nonrigid_version23/functions_nonrigid', ...
     'MiscTools/nonrigid_version23/images', ...
     'MiscTools/nonrigid_version23/low_level_examples', ...
     'MiscTools/pmkmp', ...
     'MiscTools/subtightplot', ...
     'MiscTools/thin_plate_splines', ...
     'MiscTools/tpsWarp', ...
     'MiscTools/tpsWarp/data', ...
     'MiscTools/tpsWarp/doc', ...
     'MiscTools/tpsWarp/tst', ...
     'PointMatchGMMREG_jn', ...
     'PointMatchGMMREG_jn/sourcecode', ...
     'PointMatchGMMREG_jn/sourcecode/C++', ...
     'PointMatchGMMREG_jn/sourcecode/MATLAB', ...
     'PointMatchGMMREG_jn/sourcecode/MATLAB/GaussTransform', ...
     'PointMatchGMMREG_jn/sourcecode/MATLAB/auxilliary', ...
     'PointMatchGMMREG_jn/sourcecode/MATLAB/registration', ...
     'PointMatchGMMREG_jn/sourcecode/Python', ...
     'PointMatchGMMREG_jn/sourcecode/Python/c_extension', ...
     'PointMatchGMMREG_jn/sourcecode/data', ...
     'PointMatchGMMREG_jn/sourcecode/data/face_data', ...
     'PointMatchGMMREG_jn/sourcecode/data/fish_data', ...
     'PointMatchGMMREG_jn/sourcecode/data/output', ...
     'TimeAlignment', ...
     'TrackingCodes', ...
     'WormSegmentation', ...
     'WormStraighteningCode', ...
     'behavior', ...
};

paths = strjoin(paths, ';');
addpath(paths);
